"""
Die sticker IDs

Created by Jesús Jiménez Sánchez.
"""

ONE = 'CAACAgIAAxkBAAEDxZ9h9TLsENHqeHlZ4Qfk9g3g_MgTzAACZgADH-gNNDgwae27jmsOIwQ'
TWO = 'CAACAgIAAxkBAAEDxaFh9TOH1DtacL00Oy8FQ2aXtPmzqgACZwADH-gNNI0RXkdTtPuIIwQ'
THREE = 'CAACAgIAAxkBAAEDxaNh9TOSr2WEqvmq_ge0jDf4SmE-AgACaAADH-gNNKEG5HD-72OvIwQ'
FOUR = 'CAACAgIAAxkBAAEDxaVh9TOfTIg1TAABPJxfXbSOkZSCleEAAmkAAx_oDTQ0flPBcKP7oiME'
FIVE = 'CAACAgIAAxkBAAEDxadh9TOyVJ1rhlUaHES2rMJufDKfKQACagADH-gNNIqCJQojvM8VIwQ'
SIX = 'CAACAgIAAxkBAAEDxalh9TO__XDBQH6F5oJPEfYRT-q0ngACawADH-gNNMUbrbdUw-GMIwQ'
ALL = [ONE, TWO, THREE, FOUR, FIVE, SIX]
